# Generated by Django 2.2.16 on 2022-05-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_added_fields_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
