# Generated by Django 2.2.16 on 2022-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_added_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmations_code',
            field=models.CharField(blank=True, max_length=37, null=True, verbose_name='Код подтверждения для поулчения токена'),
        ),
    ]
